leftnav:
- identifier: ba012e71-a606-bfb2-6f3f-a5a0a6f3a385
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: db417be6-df36-8d9d-c26d-e9e0c8618a60
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: e920ab11-c1db-c839-4add-8761e524e740
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 7d70ed88-1800-6902-1de5-3b7aa21c9465
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: c395471b-2707-dcbb-5013-64a7fff79710
  name: Exams
  pageRef: /pages/exams
  weight: 50
